version: "3"
services:
  mongo:
    image: mongo:4.4.0
    container_name: hox-mongo
    ports:
      - 27017:27017
    volumes:
      - "./data:/data/db"
    networks:
      - hox

  mongo-test:
    image: mongo:4.4.0
    container_name: test-hox-mongo
      - 27017:27017
    volumes:
      - "./data.test:/data/db"
    networks:
      - hox

  api:
    container_name: hox-api
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - .:/home/node/app
    env_file:
      - ./.env
    ports:
      - 3000:3000
      - 9229:9229 #debug port
    networks:
      - hox

networks:
  hox:
